export const initialValue: InitialValue = {
  firstName: {
    inputType: "input",
    type: "text",
    name: "firstName",
    placeholder: "firstName",
    inputValue: "",
  },
  lastName: {
    inputType: "input",
    type: "text",
    name: "lastName",
    placeholder: "lastName",
    inputValue: "",
  },
  emailAddress: {
    inputType: "input",
    type: "text",
    name: "emailAddress",
    placeholder: "emailAddress",
    inputValue: "",
  },
  mobileNumber: {
    inputType: "input",
    type: "text",
    name: "mobileNumber",
    placeholder: "mobileNumber",
    inputValue: "",
    options: [{}],
  },
  age: {
    inputType: "selectDate",
    type: "text",
    name: "age",
    placeholder: "age",
    inputValue: "",
    options: [{ 1: "2002" }, { 2: "2003" }, { 3: "2004" }, { 4: "2005" }],
  },
  month: {
    inputType: "selectDate",
    type: "text",
    name: "month",
    placeholder: "month",
    inputValue: "",
    options: [
      { 1: "January" },
      { 2: "February" },
      { 3: "March" },
      { 4: "April" },
      { 5: "May" },
      { 6: "June" },
      { 7: "July" },
      { 8: "August" },
      { 9: "September" },
      { 10: "October" },
      { 11: "November" },
      { 12: "December" },
    ],
  },
  date: {
    inputType: "selectDate",
    type: "text",
    name: "date",
    placeholder: "date",
    inputValue: "",
    options: [
      { 1: "1" },
      { 2: "2" },
      { 3: "3" },
      { 4: "4" },
      { 5: "5" },
      { 6: "6" },
      { 7: "7" },
      { 8: "8" },
      { 9: "9" },
      { 10: "10" },
      { 11: "11" },
      { 12: "12" },
    ],
  },
  country: {
    inputType: "select",
    type: "text",
    name: "country",
    placeholder: "Your country",
    inputValue: "",
    options: [
      { 1: "Georgia" },
      { 2: "United State " },
      { 3: "Brazil" },
      { 4: "Chile" },
      { 5: "Germany" },
    ],
  },
  city: {
    inputType: "select",
    type: "text",
    name: "city",
    placeholder: "city",
    inputValue: "",
    options: [
      { 1: "Tbilisi" },
      { 2: "Washington DC" },
      { 3: "Brazil" },
      { 4: "Santiago" },
      { 5: "Berlin" },
    ],
  },
  gender: {
    inputType: "radio",
    type: "text",
    name: "gender",
    placeholder: "gender",
    inputValue: "",
    options: [{ 1: "Male" },{2:"Female"}],
  },
};
